version: 0.2

env:
  variables:
    BUILD_ENV: "dev"

phases:
  install:
    runtime-versions:
      nodejs: 12.x

    commands:
      # temporary fix of YARN cert issue
      # TODO: clean it up...
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      -
      # Update packages.
      - apt-get update -y -q

      # Install @angular/cli and app dependencies.
      - echo Installing source NPM dependencies...
      - npm install -g @angular/cli
      - npm --prefix ./client install

  build:
    commands:
      # Build Angular application.
      - echo Build started on `date`
      - npm --prefix ./client run build:${BUILD_ENV}
      - echo Application build is successfully completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: './client/dist*'
  discard-paths: yes

cache:
  paths:
    - '/**/*'
