version: "3.8"
services:
    quote-service:
        build:
            context: ./
        ports:
            - "8080:8080"
    nginx:
        restart: always
        build:
            context: ./nginx-configuration
        ports:
            - "80:80"
            - "443:443"
            - "3000:3000"